### PR TITLE
Add spawn timer to nest pokemon

### PR DESCRIPTION
**Pull request by Obihoernchen**
Adds spawn point timer to nest map

image

TODO:
- [x] better layout
- [x] Translation
- [x] test timer values
- [ ] add a 1h progress bar as well?

## Types of changes
- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by pki0** [comment]
@Obihoernchen 

Maybe we can add additional info "possible spawntime" on the infowindow because it's only 25% chance to be there:

```
Pokemon_name: XX per day
Possible Spawn Minute: T0 to T1
Chance to find here: XX/24 %
``` 

Also progressbar could be nice. But in which style? 
Grey if not inside spawntime and percentage-green/grey if inside spawntime?

**Comment by Obihoernchen** [comment]
I was thinking about a progress bar from 0 to 60min and then mark the active time.
Like this:
 ```
<     =======   >
```
It would be :20 to :50 for instance.
I think it's way easier to compare bar positions than comparing multiple timestamps, because people probably want to find overlaps between different spawn points, so they can time their walks ;)

The chance to find idea is nice!

**Comment by titanicboyke** [comment]
works fine ;-)
nestmap-timer

**Comment by pki0** [comment]
What about the " :50".
Wouldn't it be more clear to say somthing like:
Spawn minute: 50 to 20 instead of :50 to :20
Just my opinion, most users asking what :50 means because it's very unclear also in RM

**Comment by SiteEffect** [comment]
@pokemonkiel 100% agree, this bugs me hard in RM.

**Pull request merged**
