### PR TITLE
Fix for subfolders

### PR DESCRIPTION
**Pull request by Obihoernchen**
This should fix all remaining issues with a subfolder setup (#12).

RewriteBase in htaccess have to be adjusted to use subfolders so documentation update is needed.
Or maybe someone knows a better solution. I'm not a frontend/php guy :D

So please review this carefully ;)

### CODE REVIEW

**Comment by Obihoernchen** [comment]
Just added a small css fix as well because the blue glow behind pokemons didn't work.

**Comment by jasonhemu** [comment]
Thanks for the fix. The index is working now. However, the gym page and pokestop page are still broken.

**Comment by brusselopole** [comment]
Hi, 

I've implemented some of your corrections in commit https://github.com/brusselopole/Worldopole/commit/70d2a474cfc21a00a479da5c734206c4fca37a74 https://github.com/brusselopole/Worldopole/commit/aa32a80b2724eb09997bf9943905f0a83de6ec6c & https://github.com/brusselopole/Worldopole/commit/fd985cb1c4b5a20f1ee6e7290cc8cd2f2ee462ca 

Let me know if there's still issue!

**Comment by Obihoernchen** [comment]
@brusselopole Hey, thank you :) All subfolder stuff seems to work fine now!

But the blue glow isn't fixed for me. See: https://github.com/brusselopole/Worldopole/commit/7338617313de421dc0c82cb10b84d32b65e08fbe

**Comment by Obihoernchen** [comment]
@brusselopole the blue glow is still an issue in your repo (see above) :(

**Pull request closed without merging**
