### PR TITLE
Time distribution chart now working

### PR DESCRIPTION
**Pull request by edgarborja**
Fixed query; used integer keys to fetch data.

### CODE REVIEW

**Comment by brusselopole** [comment]
Apparently if I deploy this version the single pokémon page is broken. 
What would you do?

**Comment by edgarborja** [comment]
@brusselopole 

What version of MySQL and PHP are you on? I keep finding small changes that are needed on my setup.

The $key variable, for example, was a string originally, but needs to be an int in my case.

**Comment by brusselopole** [comment]
```
amaury@sqlhost:~# mysql --version
mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) using readline 6.3
```

```
amaury@webhost:~# php --version
PHP 5.6.23-0+deb8u1 (cli) (built: Jul 12 2016 07:33:16) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

```

**Comment by edgarborja** [comment]
I'm on MySQL 5.7, maybe that is the issue.

**Comment by aastroza** [comment]
I have MySQL ver 14.14 and PHP 5.6 but my charts are not working :( 

http://santia-go.cl/pokemon/23

Maybe do I need to use your changes @edgarborja ? 

EDIT: I found the solution. You need to disable the "ONLY_FULL_GROUP_BY" mode.

msql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

**Pull request closed without merging**
