### PR TITLE
Trainer level distribution chart

### PR DESCRIPTION
**Pull request by Obihoernchen**
Add a trainer level distribution chart per team to dashboard page.
## Description

If result is empty (gym-info disabled) the graph doesn't show up.
### Requirements

Have gym-info enabled in PokemonGo-Map
## Motivation and Context

Implements https://github.com/brusselopole/Worldopole/issues/47
## How Has This Been Tested?

Locally with full and empty trainers table (same as gym-info on/off)
## Screenshots (if appropriate):

image
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Obihoernchen** [comment]
Please review it :)

**Comment by AL-dot-debug** [comment]
You need to do 2 tests. 
The first you did is perfect to hide the dash if there's no data but you'll also need to not display javascript when there's no data or you'll create errors as your trainver_lvl array does not exist 

`PHP Notice:  Undefined offset: 1 in /home/git_brusselopole/gym_test/core/js/dashboard.graph.js.php on line 617, referer: http://localhost/gym_test/dashboard`

I'll change the workers config and see w/ datas

**Comment by AL-dot-debug** [comment]
With the gym data, it is per-fect ! 
I love the chart but as it's live data, shouldn't it be on the gym page in place of the dashboard?

**Comment by Obihoernchen** [comment]
yeah I thought about this as well.
I'll transfer it to gym page ~~and we can compare both!~~ nope gym page is much better. No need to compare :D

**Comment by Obihoernchen** [comment]
On gym page now :)
image

**Comment by Obihoernchen** [comment]
@56k-amaury all done :)

**Comment by nikos90** [comment]
Nice job!
A small bug:

in the js file

`# only if data isn't empty
        if ($data) {
            # fill empty levels counts with 0
            for ($i = 5; $i <= 40; $i++) {
                if (!isset($data[$i])) {
                    $data[$i]=0;
                }
            }
            # sort array again
            ksort($data);
            $trainer_lvl[$teamid] = $data;
        }else{
            $trainer_lvl[$teamid] = [];
        }
`

if a team has not trainers in db the js was throwing an error

**Comment by Obihoernchen** [comment]
@nikos90 thanks!
See 4b15d623d3a3349cb5a822e16733f4db7da6e811
I had to use a slightly different approach to fix this. Your change would break the graph hiding.

**Comment by nikos90** [comment]
I see!
Nice one!

**Comment by AL-dot-debug** [comment]
Perfect 👍

**Pull request merged**
