### PR TITLE
Add ingame Pokemon images: _go.png

### PR DESCRIPTION
**Pull request by pki0**
## Description
- Add ingame sprites
- Resized all to 250x250
- Better Weedle quality
- Resized to 215x215 and padding 15x15 added
- Looks better now in Pokedex! Thanks

## Screenshots
- Looks awesome on map
map

- Looks good in trainer page
images

bildschirmfoto 2017-02-12 um 11 46 50

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by tobias86aa** [comment]
Yes it sure looks awesome on the map :)

**Comment by Obihoernchen** [comment]
Could you add 15px padding to all images? Then it would look like all the other ones. They use 15px padding as well.

**Comment by pki0** [comment]
Done. Ready to merge :)

**Comment by Obihoernchen** [comment]
Awesome stuff!

**Pull request merged**
