### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by WojtekK78**
## Description

Polish translation
## How Has This Been Tested?

http://warszawa.pokemonfun.pl
## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Obihoernchen** [comment]
Holy shit you are awesome! 
Thank you! 
Please add pl to variables.examples.json and I'll merge it :) 
+1

**Comment by WojtekK78** [comment]
Added change to  variables.examples.json

**Comment by Obihoernchen** [comment]
@WojtekK78 why did you close it? Is there any issue with this PR?

**Comment by WojtekK78** [comment]
sorry didn't notice closing it

**Comment by Obihoernchen** [comment]
Ahh please do not add other stuff to this branch :/ can you revert the analytics stuff please?

**Comment by WojtekK78** [comment]
oops, sorry first time using Github, one second

**Comment by WojtekK78** [comment]
Let me close that PR and create new clean only for translations

**Pull request closed without merging**
