### PR TITLE
Trainer page

### PR DESCRIPTION
**Pull request by Obihoernchen**
Credits go to @PoUpA and paul :heart: 

I did just a few changes and improvements.

## Description
see Screenshot

## Motivation and Context
It's super awesome!

## How Has This Been Tested?
https://vserver.obihoernchen.net/pokemon_dev/trainer

## Screenshot:
image

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Obihoernchen** [comment]
~~Ideas: Show team as well (maybe as row background color? or a symbol?)~~
Done

**Comment by fusenuk** [comment]
If you have a page set up to show the gym detailed info then a nice addition to this trainer page is to pull the gym data for each pokemon

```
$reqPkms = "SELECT DISTINCT m.gym_id, p.pokemon_uid, p.pokemon_id, p.cp, p.iv_defense, p.iv_stamina, p.iv_attack
                    FROM gympokemon as p, gymmember as m
                    WHERE trainer_name = '".$trainer->name."'
                    AND m.pokemon_uid = p.pokemon_uid
                    ORDER BY cp DESC";
```

I then use the CP value as a link

`<p class="pkmn-name"><a href ="gyminfo/<?= $pokemon->gym_id ?>">CP: <?= $pokemon->cp ?></a></p>`

**Comment by Obihoernchen** [comment]
@fusenuk yeah that's cool but I don't want to add something like this to Worldopole, because you could snipe gyms from specific trainers with this change easily. I would like to keep it kind of anonymous.

**Comment by Obihoernchen** [comment]
~~**TODO**: Move trainer graph to trainer page?~~
Done

**Comment by Obihoernchen** [comment]
Here we go

**Pull request merged**
