### PR TITLE
Add Dark & PoGo style to Pokemon/Pokestop/Gym map

### PR DESCRIPTION
**Pull request by pki0**
## Description

- Add nice dark style to have a better and more clear view on heatmap.
- Add dark style to all other maps.
- Disable "street view" button on all maps.
-Add PoGo Style to all maps

- When changing from "Heatmap" to "Live" always default (light) style is enabled. (Better view)

## How Has This Been Tested?

My page.

Live demo example:
https://beta.pokemonkiel.de/pokemon/41
## Screenshots:
bildschirmfoto 2017-02-06 um 16 21 24
bildschirmfoto 2017-02-06 um 20 31 49

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by SiteEffect** [comment]
Best way to toggle? Of course a variables.json flag ``map_style: light/dark`` but how to switch between them in code? How about complete different map files to link to accordingly to setup variable, by php?

**Comment by pki0** [comment]
Default is always old style.
So you want an option to set dark_style as default?

**Comment by SiteEffect** [comment]
No, I meant how to enable dark in general? With the option to switch back.

**Comment by pki0** [comment]
So now there are two options to switch styles in the top left of the maps.
With "Dark" you have three options to switch styles.

So you want an option to disable "dark" and still have the two options?

**Comment by SiteEffect** [comment]
I did not see the option to switch to ``Dark`` in the top left. In that case, it's fine like it is now :-)

**Comment by pki0** [comment]
bildschirmfoto 2017-02-06 um 17 08 07

@Arengo 

Edit: Ah okay I think you found it now 👍

**Comment by Obihoernchen** [comment]
What's about adding all style definitions to variables.json (or a new file called mapstyles.json), so we don't have to write such a lot of duplicate code?

**Comment by pki0** [comment]
@Obihoernchen Good point. But I don't know if that is possible.
Even RocketMap has the styles in map.common.js and not separated.

Reading this tells me the same:
http://stackoverflow.com/questions/27919910/using-json-files-in-google-maps-styling

Here is an example with single style.
http://embed.plnkr.co/IVCPxBVemL3pWxTyVypU/
(Maybe it works)

Maybe we could use single files for each style but thats not saving so much code.

If you have an idea please tell me.

**Comment by Obihoernchen** [comment]
I'll take a look at this during the weekend and try some stuff. 
If you come up with some cool trick before, feel free :)

**Comment by pki0** [comment]
@Obihoernchen Done. Feel free to test it!

Styles are now in separated files but still a lot duplicate code because of loading the files.

**Comment by Obihoernchen** [comment]
Cool stuff will have a look at it thanks :+1:

**Comment by Obihoernchen** [comment]
works fine :+1: 
Thank you very much!

**Pull request merged**
