### PR TITLE
Show mythic recent spawns only

### PR DESCRIPTION
**Pull request by Obihoernchen**
_Note: Reopen of #85_ 

I think it's more interesting to have some mythic pokemons in the recent spawn list.
All these pidgeys and rattatas are boring.
## Description

This will use rarity from `pokelist_XX.json` and the SQL will filter for mythic pokemon IDs.

**Update: You can switch this on or off now**
## Motivation and Context

Make it more interesting
You may be able to catch a rare pokemon because of this ;)
## How Has This Been Tested?

locally with english and german: 
https://vserver.obihoernchen.net/pokemon/
## Screenshots:

Before
image

After
image
## Types of changes

- [X] Breaking change (fix or feature that would cause existing functionality to change)
## TODO
- Translations for other languages
- We really should improve this whole json translation/pokelist stuff :D See https://github.com/brusselopole/Worldopole/issues/81#issuecomment-250943283 as well.

What do you guys think about this PR? Let's discuss.

### CODE REVIEW

**Comment by fusenuk** [comment]
I like the idea but I think it should be a choice/or show both rows

**Comment by Obihoernchen** [comment]
@fusenuk yeah sounds good. Let me add some lines ;)

**Comment by Obihoernchen** [comment]
Note: I should add error handling if there is no mystic pokemon found

**Comment by Obihoernchen** [comment]
Not2: link css seems to be buggy on mobile. Have to fix it.

**Comment by SiteEffect** [comment]
The "Fix" brakes it for my non-empty database.

**Comment by SiteEffect** [comment]
Fix for the fix: mysql_num_rows --> mysqli_num_rows

**Comment by Obihoernchen** [comment]
Should work fine now. Let's go

**Pull request merged**
