### PR TITLE
Add candies translation

### PR DESCRIPTION
**Pull request by Zegorax**
Sorry for second PR, I didn't see it wasn't translated as well.
## Description

Made the word "Candies" available for translation.
## Motivation and Context

Just improving the project
## How Has This Been Tested?

Dedicated servers
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by ItsCEED** [comment]
I think they should stay as Candies, did the first PR for Candies and No of Candies and i leave them as that on purpose

**Comment by Obihoernchen** [comment]
Why? Ingame it's translated as well. 
+1 for merge

**Comment by Zegorax** [comment]
I'm still waiting for the merge, any update @56k-amaury ?

**Comment by AL-dot-debug** [comment]
Merged ;)

**Pull request merged**
