### PR TITLE
Add page to explore all changes of gyms over time

### PR DESCRIPTION
**Pull request by michikrug**
## Description

Since I was always curious of what is happening in the gyms in my town, but no historical data is tracked by RocketMap, I have added a new SQL table that does so.
Using the MySQL scheduler, every 20secs the data from the "gym" table is added to the new "gym_history" one.
This data is then nicely represented on a separate new page. /gymhistory
The data is searchable, sortable and filterable.

## Motivation and Context

Now you are able to see, when gyms are leveled up or down and which Pokémon are placed in or thrown out.
(This will also show you all those losers, who are using multiple accounts to shave their spot into high level gyms. There is a separate branch that extracts such behavior.)

## How Has This Been Tested?

Tested in my own Worldopole online instance.
Does not interfere with any other functionality.

It is necessary to execute some SQL statements that I have documented in readme.gymhistory.md to create the new table and the update events.
Furthermore, you have to enable the MySQL event scheduler. This is also documented in the readme for a running server, but you should also update your server configuration to enable the scheduler on start.

Remark: it does not include any localization so far -> english only

## Screenshots (if appropriate):
bildschirmfoto 2017-05-08 um 12 37 48

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## TODO
- [ ] Localization

### CODE REVIEW

**Comment by SiteEffect** [comment]
Awesome!

**Comment by myntath** [comment]
This is pretty cool. I've been using it without problem so far, my sql is not good enough to review properly. Personally I really like the option to click a users name and be taken to their trainer page. However, it seems that in the past it may have been a deliberate decision not to show which gyms a trainer is in (both on the trainer page and the gym page). Can anyone say if this is infact a deliberate decision? If so you should probably remove the names and links. This would suck but I can see the reasoning is likely to prevent people being targeted. Perhaps we could have a config variable for showing names? Then in separate PR this could also affect showing names on the gym page and showing gym names on the trainer page.

**Comment by Obihoernchen** [comment]
Let's do a vote for trainer name <-> gym linking. See discord #announcements

**Comment by mpw1337** [comment]
Any way to do this without the MySQL event scheduler? I don't have the privileges to enable that on my server (it's only an additional DB from a webhoster, but works for most of the things)
Doesn't need to update every 20 seconds, 1-5 minutes is fine too, with a cron job maybe?

**Comment by michikrug** [comment]
@mpw1337 Sure. Just run the queries stated in the event using a cron job. A short interval is adviced to get all changes.

**Comment by Obihoernchen** [comment]
What's the status here?

**Comment by z0n** [comment]
This has been working fine here (https://pokekarte.de/gymhistory) for a while. 
One thing I noticed is that while it's possible to search for special characters (I tried ä, ö and ü) in gym names, it's not possible to do this using the URL as the browser (at least Chrome) always converts them to `uuml;` etc. If this would be fixed you could directly post links to specific gyms.

**Comment by michikrug** [comment]
Currently broken due to massive gym changes in game.

**Comment by ghost** [comment]
@michikrug Do you think you'll ever work on this again?

**Comment by michikrug** [comment]
@blakewenloe I already updated it on my site long time ago and it is working fine so far

I will push the changes in the next days

**Pull request closed without merging**
