### PR TITLE
Improvements + Live pokemons

### PR DESCRIPTION
**Pull request by PoUpA**
## Description
Added live map on pokemon page, you can filter the displayed pokemons by Iv
Improved loading of pokedex page (load spawn count after loading the page)
Improved loading of pokemon page (better SQL for spawn rate and load graph of spawn after loading the page)
Improved search on trainer page for mobile
Minor fixes in dashboard.graph.js.php (variables initialisations mostly)

## How Has This Been Tested?
localhost on chrome

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by ItsCEED** [comment]
Been awhile since i contribut or something, but i love how ppl are contributing to this! Keep up the good job!

**Comment by PoUpA** [comment]
we will, if srutinizer let us  😉

**Comment by SiteEffect** [comment]
Seems really good!

**Review by Obihoernchen — CHANGES_REQUESTED** [review]
- [X] Please use a normal html link for the trainer name instead of js event in trainer table
- [X] pokemon live view needs a no iv option

**Review by Obihoernchen — APPROVED** [review]

**Pull request merged**
