### PR TITLE
Ajax loading for trainers

### LINKED ISSUE #98: [Feature Request] Dynamical loading "alltrainer" page
## Expected Behavior

Follow a second button "Full list" instead of "Search" on "trainer" page to obtain a full view of all trainers, without their Pokémon, which loads around 50 trainers dynamically when scrolling further down. This list can be sorted by "name","level" and "gym Pokémon".

## Current Behavior

We just have the top 30 (for some pages top 100) list which is nice for the top player but uninteresting to watch for all the other user.

## Possible Solution

Create a new page "alltrainer.page.php" with less content of detail for the trainer div-pattern. Change data.loader.php or ajax to handle the desired job. Also possible to cache this page every X hours wie cron to take stress from the DB. Quick implementation by copy/paste the trainer page data loader and some deprecations of Pokémon CP, IVs etc. for the DB request.
Implement sort options, clickable by column label, by using multisort and reload list.

name: name->level
level: level->gym Pokémon
gym Pokémon: gymPokémon -> level.

### PR DESCRIPTION
**Pull request by PoUpA**
## Description
Load trainers dynamicaly with "infinite scroll"

## Motivation and Context
fix #98 

## How Has This Been Tested?
Localhost on chrome and firefox

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by SiteEffect** [comment]
Voting for sorting option. Too busy right now to contribute myself, sorry 👎

**Comment by Obihoernchen** [comment]
Ok I tested it. First of all it looks nice :+1: 
But I found 3 small issues:
- Trainer level distribution is still shown when searching for a trainer name
- would be nice to see an animation every time something is loading
- my browser seems to die :dagger:

**Comment by PoUpA** [comment]
corrected 2 of the issues (Trainer level distribution is still shown when searching for a trainer name & my browser seems to die 🗡 <=== please test it to see if it's better)
btw animation is there ... but chrome seems to mess it up ... loading spinner show on firefox when loading next page

**Comment by Obihoernchen** [comment]
Seems to be better now :+1: 

A few suggestions:
- center CP text
- load only 10 items at a time instead of 30. 30 is too much I think ;)
- a search with empty input should show the trainer level graph
- "Rank" seems to be buggy? It shows some ranks twice and skips some ranks?
- Do not load trainer graph and scripts at all instead of hiding/removing it. Like it was before. Is this possible?
```php
<?php
// show only if there was no search for a specific trainer
if ($trainer_name === "") { ?>
	<div class="row area">
		<div class="col-md-12 text-center">
			<h2 class="sub-title">Trainer <strong>level</strong> distribution</h2>
		</div>
		
		<div class="col-md-12">
			<canvas id="trainer_lvl" width="100%" height="20"></canvas>
		</div>
	</div>
	<script async defer src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.1/Chart.min.js"></script>
	<script async defer src="core/js/trainer.graph.js.php"></script>
<?php 
} ?>
```

On top of that maybe we just remove the grayed out pokemons completely?
For me like 90% is grayed out anyways. So this would be a nice performance increase.
What do you think about it?

**Comment by PoUpA** [comment]
- [x] center CP text
- [x] load only 10 items at a time instead of 30. 30 is too much I think ;)
- [x] a search with empty input should show the trainer level graph
- [x] "Rank" seems to be buggy? It shows some ranks twice and skips some ranks?
Rank is the number of people with the same or better rank so it work perhaps should we call it differently
- [x] Do not load trainer graph and scripts at all instead of hiding/removing it. Like it was before. Is this possible?
As the page doesn't reload anymore this is not really possible. hiding and showing is the way to go 


And I don't think it's a good idea to remove pokemons out of gym. People use it to share IV. A solution can be to load only actives on listing and add a button on each trainer to load inactives pokemons

-

**Comment by Obihoernchen** [comment]
Cherry-pick merged :+1: 
Awesome work!

**Pull request closed without merging**
