### PR TITLE
[InProgress] Add Pokémon information for generation 3 to 7

### PR DESCRIPTION
**Pull request by michikrug**
## TODO
- [ ] Other Languages than EN/DE
- [ ] Images for all new Pokémon in all variants /o\
- [ ] Add information about moves
- [ ] Update ratings
- [ ] Add basic stats for gen 4 - 7 when they are available

## Description
Add all basic stats and information for the new Pokémon generations.

## Motivation and Context
We will soon see new Gen. 3 Pokémon starting on Halloween.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by z0n** [comment]
This needs to be updated to 5441 (Slaking's max CP) if we're just considering Pokémon up to gen 3:
https://github.com/brusselopole/Worldopole/blob/84036338c193cadac07a615b0dd529327a1e0ab5/core/process/data.loader.php#L117


Also, I think we should limit the related Pokémon on the bottom of the Pokémon pages to the currently active generation:
https://github.com/brusselopole/Worldopole/blob/84036338c193cadac07a615b0dd529327a1e0ab5/core/process/data.loader.php#L172

-> `if (in_array($type, $types) && $pokeid <= $config->system->max_pokemon) {`

Marshadow's picture is still missing as it's not on pokemon.com yet. This should do:

**Review by Obihoernchen — APPROVED** [review]
Let's merge this for now for Gen 3 support. We will do some further improvements in new PRs.

**Comment by darkelement1987** [comment]
Hi when will Gen 3 ratings be updated? It's been 3 months by now lol. And what were the existing ratings based on? I'll be happy to give all pokemon their right ratings if you can point me in the right direction.

**Comment by Obihoernchen** [comment]
@DarkElement1987 it's based on https://pokemongo.gamepress.gg/pokemon-list

But it looks like they use 1-5 instead of 1-10 now.
Feel free to submit a PR with updated ratings :)

**Comment by darkelement1987** [comment]
Ill update later on today!

Op 22 jan. 2018 01:03 schreef "Obihörnchen" <notifications@github.com>:

**Comment by darkelement1987** [comment]
How did you handle ratings like -/10

Op 22 jan. 2018 01:03 schreef "Obihörnchen" <notifications@github.com>:

**Comment by Obihoernchen** [comment]
Calculated them based on CP iirc.

**Comment by darkelement1987** [comment]
I made new ratings. Please check pm on discord. I'm not sure on how to upload them here the right way.
I used this page as source: https://pokemondb.net/pokedex/all

**Pull request merged**
