### PR TITLE
Gym improvements

### PR DESCRIPTION
**Pull request by PoUpA**
## Description
Added progress bar for gym level

## How Has This Been Tested?
chrome and firefox

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by Obihoernchen — CHANGES_REQUESTED** [review]
Cool :+1: 
But I would like to request a few changes:
- There is `<div id="levelMeter">` twice (gym.page.php)
- Labels seem to be a bit off:
image
Maybe labels on the progress bar itself look better? Dunno if it's possible to fit them.
Something like this for example (just a fast hack without correct colors etc):
image
- We should try the brighter color I think (see trainer page border). Looks better.
- Prestige text should be smaller than gym title (14px maybe)

**Comment by PoUpA** [comment]
Good ideas 👍  I will try to make the changes after my work

**Review by Obihoernchen — APPROVED** [review]

**Review by Obihoernchen — CHANGES_REQUESTED** [review]
Looks awesome now :+1: :+1: :+1: 
`.team_background_[1-3]` is unused.
Please fix then I'll merge :)

**Comment by PoUpA** [comment]
fixed ;)

**Review by Obihoernchen — APPROVED** [review]

**Comment by Obihoernchen** [comment]
argh hit the wrong button... now there is a huge git mess xD

**Comment by PoUpA** [comment]
did I made a mistake ?

**Pull request merged**
