### PR TITLE
Remove slash in meta URLs, fix some titles and nests meta URLs

### PR DESCRIPTION
**Pull request by michikrug**
Removed redundant slash in meta URLs, since the slash is already in the HOST_URL variable.
Fixed some text problems and meta URLs of nests page.

## Description

- Removed the slash after HOST_URL in every meta URL
- Fixed wrong meta URLs of nests page
- Removed duplicated white space in pokemon page title by changing translations

## Motivation and Context

Make code look good.

## How Has This Been Tested?

Own Worldopole instance.

## Screenshots (if appropriate):
None. Since only code changes.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by pki0** [comment]
Removing the spaces between: <?= $locales->FIND ?> and <?= $pokemon->name ?> will not result in:
"FindSnorlax in ... " ? 
I'll test this with the Telegram Meta-Bot later

Edit: Oh I see that all translation files have: "FIND" : "Find " .
Wouldn't it be better to fix this directly in translation files?

**Comment by michikrug** [comment]
No, because of translation files stating: "FIND": "Find "

We could otherwise change all the translations. But this maybe affect also other pages.

**Comment by michikrug** [comment]
At least the Github search finds no other use of FIND than in the meta file.
So we could change all the translations.

**Comment by Obihoernchen** [comment]
+1 and I'll merge

**Review by Obihoernchen — APPROVED** [review]

**Pull request merged**
