### PR TITLE
Adding toggle for different monster icons

### PR DESCRIPTION
**Pull request by SiteEffect**
This PR is directly an addition to the PR #159 - New PNG-Images  

## Description

Adding a toggle and changing the wanted-icon locations that the existing code does not have to be changed much. We rely in many different ways on the current icon structure and location.

## Motivation and Context

Add a toggle and let the user decide which icons they want to have for their little monsters

## How Has This Been Tested?

Has to be tested! Please help. The initial location of the icons is important, yet.

## Types of changes

- [x] New feature (See #159 )
- [x] Breaking change (exisiting function still works but is now a bit extended)

### CODE REVIEW

**Comment by pki0** [comment]
Wouldn't it be better to do it like this instead of create another folder? :

IMG names:
1.PNG for old images
1_flat.PNG for new images
and so on.

Every time an image is loaded by the code put the 
`if ($config->system->artificial_icons)`
and then add the suffix to image source.

In my opinion better then remove a dir by the code (could be dangerous)

**Comment by Obihoernchen** [comment]
@klatterhans yep I agree. I was thinking about something like:
```
pokeimg_suffix: ""
pokeimg_suffix: "_flat"
```
Then load image like `$pokeid.$config->$system->$pokeimg_suffix.".png"`

This is even more flexible and needs less code. We could add more icons in the future easily.

**Comment by pki0** [comment]
@Obihoernchen Yes this is exactly what I meant with you suffix. But your way is more intelligent 👍 

And there are not many cases:
Homepage
Pokedex
Pokemonpage
Trainerpage
Gympage

**Comment by Obihoernchen** [comment]
Implemented in #159

**Pull request closed without merging**
