### PR TITLE
Add Pokemon ID to Pokedex

### PR DESCRIPTION
**Pull request by pki0**
## Description
- Possible setting to show Pokemon ID in Pokedex
- Trying to display Pokedex like ingame
- You can now find Pokemon in serach bar by Pokemon ID
- Toggable because not everyone will like it

## Screenshots (if appropriate):
bildschirmfoto 2017-04-10 um 11 03 35

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by Obihoernchen — CHANGES_REQUESTED** [review]
Please remove the pokedex_numbers config option and use pokedex numbers per default.
All people on discord voted for it :+1:

**Review by Obihoernchen — APPROVED** [review]

**Comment by Obihoernchen** [comment]
My last commit changes:
image
to
image

**Comment by titanicboyke** [comment]
rare

**Comment by titanicboyke** [comment]
ids

**Pull request merged**
