### PR TITLE
Corrected errors and bug (firefox) in trainers page

### PR DESCRIPTION
**Pull request by PoUpA**
## Description
When clicking a trainer name in firefox causes to load the trainer twice.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by Obihoernchen — CHANGES_REQUESTED** [review]
Please move the two trainer.page.php scripts to index.php like all the other scripts.
There is no reason anymore to have them in trainer.page.php (I overlooked that).

On top of that can we change pokestops.maps.js ajax call to async as well? I think so.

Than I'm going to merge this immediately.
Thank you :+1:

**Comment by Obihoernchen** [comment]
Yay async loading fixes the loading animation in Chrome as well :champagne:

**Review by Obihoernchen — APPROVED** [review]

**Comment by Obihoernchen** [comment]
@PoUpA What's the reason for removing `async defer` from all map scripts?

**Comment by PoUpA** [comment]
@Obihoernchen quarter of the time they gave me errors and didn't loaded

**Pull request merged**
