### PR TITLE
Dashboard graph fixes (fix #100)

### LINKED ISSUE #100: Dashboard Pokémon total spawn/Lure graphs are not only 7 days
## Expected Behavior

+ Pokémon total spawn graph shows last 7 days
+ Lure graph the same
+ Read the times/dates on the X axis 
## Current Behavior

Pokémon total spawn graph shows all days and is slow as hell
## Possible Solution

+ For last 7 days:

In dashboard.graph.js.php:

Around line 50:

+ add $lastweek
+ add if condition for $lastweek

```
$now		 = time(); 
$yesterday	 = $now-86400; 
$lastweek        = $now-604800;
$i=0; 

foreach($stats as $data){
	
	if($data->timestamp > $lastweek){

	$labels_global[]	= '"'.date('d/m h:i a', $data->timestamp ).'"';
	$total[]                    = $data->pokemon_now;
    }
	
if($data->timestamp > $yesterday){
```
And for lure:

```
    if($data->timestamp > $lastweek){
	
		$labels_stops[]			= '"'.date('d/m - h:i a', $data->timestamp ).'"';
		$lure[]				= $data->lured; 
	
	}
```

+ For the axes:

Current solution is to add the date to the X axis by the following:
```

if($data->timestamp > $yesterday){
		
		$labels[] = '"'.date('d/m h:i a', $data->timestamp ).'"'; 
```

and:
```

if($data->timestamp > $yesterday){
	
		$labels_gym[]			= '"'.date('d/m h:i a', $data->timestamp ).'"';
```

graph
prestige

### PR DESCRIPTION
**Pull request by Obihoernchen**
For details see #100.
- Fix for wrong timeframes
- xAxes scaling fixed for small screens
- xAxes labels improved (24h, international date)

Thank you @klatterhans and @Arengo.

## Demo
https://obihoernchen.net/pokemon/dashboard

## Screenshot
image

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Obihoernchen** [comment]
I think that's the best way to show these dates for all countries.

Is everybody happy with this?

**Comment by pki0** [comment]
1) Now you have 24h timestamp by default (Don't know if Americans can read this)

2) Your graphs are still not readable on mobile. (Same with my fix, didn't notice)

**Comment by Obihoernchen** [comment]
1) their military time is 24h so most of them should :D I just like it because it's much smaller.
2) Yeah that's kinda strange. I'll try to add some padding. 

On top of that graphs should be higher on mobile I think. Like the 24h graph for spawns. Will look into this as well.

**Comment by Obihoernchen** [comment]
not finished yet :octocat:

**Pull request merged**
