### PR TITLE
Add Raids Overview Page

### PR DESCRIPTION
**Pull request by michikrug**
**IMPORTANT NOTICE: Needs unofficial changes to RM that provide raids data**
https://github.com/RocketMap/RocketMap/pull/2102/

## Description

This PR adds an tabular overview of upcoming and current raids.
The data is taken from a not yet merged PR that provides raids data in a separate table.
The page is also optimized for mobile devices.

## Motivation and Context

This PR enables users to easily find the next high level raids and displays their bosses, if the information is available.

## How Has This Been Tested?

Tested on own instance with custom RM.

## Screenshots (if appropriate):
bildschirmfoto 2017-07-04 um 17 32 51

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by jorgitoh** [comment]
jquery.min.js:4 GET xxxxxxxxxxxxx/core/process/aru.php?type=raids&page=0 500 (Internal Server Error)

I merged all the files u changed. Should i do something more?. Using PR 2102 with raids.

**Comment by michikrug** [comment]
@jorgitoh can you please have a look what your apache/nginx error log tells?

**Comment by jorgitoh** [comment]
Hi @michikrug i found the error. We have a different table. Seb changed 2 times the BD, I have raid.start instead of raid.battle.

**Comment by Qualimiox** [comment]
Great PR overall, just a minor bug I'm having:
The linked coordinates on the map are off for some reason. I've checked multiple and they all still seem to fall inside the map area, but they're not where the raid is happening.
I didn't find the fault in the code on first glance, so just reporting the bug for now.

Edit: Just realized that the linked coordinates are correct, RocketMap just puts them at the wrong place, so this is a RM issue. If coordinates  get switched to Gmaps as proposed in #297 this issue is fixed.

Edit 2: Found the issue, URL uses **lng=** instead of **lon=**

**Comment by michikrug** [comment]
I think this is because stock RM does not support jumping to a specific location using URL parameters. Therefore you always end up at your RM default location. I did not think of that when implementing the links.

**Comment by Qualimiox** [comment]
Ahhh, just found the issue.

I was wondering, because I've already been using location URLs to create custom links for adjacent towns of my city.
Your map URL is wrong, you used **lng**= but RM expects **lon=**   

But yeah, these links still won't work if the user has "Start map at location" turned on, because that setting has priority over the coordinates URL.

**Pull request merged**
